version: '2'
services:
  web:
    build: .
    image: jiksnu
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    extra_hosts:
      - "artifactory.jiksnu.org:173.255.231.160"
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
  postgresdb:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:3
    ports:
      - "6379:6379"
  memcached:
    image: memcached
  sentry:
    image: slafs/sentry
    depends_on:
      - postgresdb
      - redis
      - sentryCeleryWorker
    ports:
      - "0.0.0.0:9000:9000"
    env_file: environment
    volumes:
      - sentry-files:/data
    links:
      - postgresdb:postgresdb
      - redis:redis
      - sentryCeleryWorker:sentryCeleryWorker
  sentryCeleryWorker:
    image: slafs/sentry
    command: celery worker -B
    env_file: environment
    environment:
      C_FORCE_ROOT: "true"
    volumes:
      - sentry-files:/data
    links:
      - postgresdb:postgresdb
      - redis:redis
volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local
  sentry-files:
    driver: local
