version: '2'
services:
  dockerui:
    image: microbox/dockerui
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/docker.sock
    # network:
    #   - backend
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
    networks:
      - backend
  etcd:
    image: microbox/etcd
    command: "--name jiksnu -data-dir=/data"
    ports:
      - "4001:4001"
      - "7001:7001"
    volumes:
      - etcd-data:/data
    # network:
    #   - backend
  memcached:
    image: memcached
    # network:
    #   - backend
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
  nginx:
    image: nginx-fork
    ports:
      - "80:80"
    volumes:
      - "./volumes/conf.d:/etc/nginx/conf.d"
      - "./volumes/vhost.d:/etc/nginx/vhost.d"
      - "./volumes/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - proxy-tier
      - backend
  postgresdb:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # network:
    #   - backend
  redis:
    image: redis:3
    ports:
      - "6379:6379"
    # network:
    #   - backend
  sentry:
    image: slafs/sentry
    depends_on:
      - postgresdb
      - redis
      - sentryCeleryWorker
    # network:
    #   - backend
    ports:
      - "0.0.0.0:9000:9000"
    env_file: environment
    volumes:
      - sentry-files:/data
    links:
      - postgresdb:postgresdb
      - redis:redis
      - sentryCeleryWorker:sentryCeleryWorker
  sentry-worker:
    image: slafs/sentry
    command: celery worker -B
    # network:
    #   - backend
    env_file: environment
    environment:
      C_FORCE_ROOT: "true"
    volumes:
      - sentry-files:/data
    links:
      - postgresdb:postgresdb
      - redis:redis
  web:
    build: .
    image: jiksnu
    # ports:
    #   - "80"
    depends_on:
      - mongo
    environment:
      JIKSNU_DB_URL: "mongodb://mongo/jiksnu_docker"
      VIRTUAL_HOST: dev.jiksnu.com
      VIRTUAL_NETWORK: nginx-proxy
    extra_hosts:
      - "artifactory.jiksnu.org:173.255.231.160"
    volumes:
      - maven-repo:/root/.m2
    expose:
      - "8080"
    networks:
      - backend
volumes:
  etcd-data:
    driver: local
  maven-repo:
    driver: local
  mongo-data:
    driver: local
  postgres-data:
    driver: local
  sentry-files:
    driver: local
networks:
  proxy-tier:
    external:
      name: nginx-proxy
#   frontend:
#     driver: host
  backend:
    driver: bridge
